### ISSUE TITLE
Very High Fee for Tranche Auction

### ISSUE THREAD

**Issue by RexTheBean** [IrrigationProtocol/BugBounty#10]
In attempting to Auction some tranched Pods, I got the following fees in my MetaMask transaction approval. A $165 fee to auction $62 worth of Pods seems... a bit steep.

![image](https://github.com/IrrigationProtocol/BugBounty/assets/145804523/dfe0e97e-fa4e-46fb-88d6-572c87995774)

**Comment by Super-Genius** [comment]
Should be fixed in the Beta, try app-beta.irrigation.finance to verify @RexTheBean
