### ISSUE TITLE
Removal of urBEAN and FRXETH. 

### ISSUE THREAD

**Issue by keshxyz1** [IrrigationProtocol/BugBounty#11]
![image](https://github.com/IrrigationProtocol/BugBounty/assets/140015897/a022df98-64c1-46b3-883b-2c160db4e1c8)
![image](https://github.com/IrrigationProtocol/BugBounty/assets/140015897/55b7dbb6-c8f4-4fd1-9bb5-443b07b675fd)

Seems like prices for urBEAN and FRXETH are currently not pulling in. If that is the case, and if we do not want to include it as part of launch, we may need to remove it.

**Comment by Super-Genius** [comment]
@ruymaster Please just fix the price oracles for these

**Comment by ruymaster** [comment]
I think we can use off-chain prices instead of on-chain. Since frxETH and urBEAN tokens are not used in Sprinkler, an on-chain price oracle is not required.

**Comment by Super-Genius** [comment]
Need to be very careful of this and have to check if price is signed by our off chain provider so it can't be manipulated

**Comment by Super-Genius** [comment]
and signed with timestamp

**Comment by ruymaster** [comment]
Our contract doesn't use offchain price, and only ui will use this offchain price. It is only to display price on UI. Even in that case, do we need signing with timestamp?

**Comment by Super-Genius** [comment]
if not used by contract, neither is needed
