### ISSUE TITLE
UI prevents creation of Bean auctions due to approval loop

### ISSUE THREAD

**Issue by safisynai** [IrrigationProtocol/BugBounty#2]
I attempted to create a Bean auction with the following parameters:
![image](https://github.com/IrrigationProtocol/BugBounty/assets/63223904/c1c36385-332b-4e3b-ba5a-755aa2a7f576)

After granting the requisite [Dai approval](https://etherscan.io/tx/0x1324ebdaa501e35504f3167af99b3af952c530758220f380f988998e60bf5c1a) the UI still shows the approve button. Refreshing the page and trying again with the same parameters still prompts for approval and thus an auction cannot be created.

This was in Firefox 119.0a1 on Windows 11, using Frame v0.6.8 as the wallet provider with MEVBlocker as the RPC.

I haven't tried to create any other kinds of auctions, so I don't know if a similar issue also impacts those.

**Comment by ruymaster** [comment]
Fixed. 
https://github.com/IrrigationProtocol/irrigation-dapp/commit/d118c69953d796ef6e3a6d818d3712e2358f7353
