### ISSUE TITLE
Sprinkler - Gas

### ISSUE THREAD

**Issue by keshxyz1** [IrrigationProtocol/BugBounty#22]
The gas figure is not appearing for this section:

<img width="1301" alt="Screen Shot 2023-09-25 at 6 13 45 PM" src="https://github.com/IrrigationProtocol/BugBounty/assets/140015897/f8b62f58-79df-431b-becd-49611d0f55e1">

**Comment by CrabsAndTaxes** [comment]
Confirmed-gas display
