### ISSUE TITLE
Required Approval to use ETH in the Sprinkler

### ISSUE THREAD

**Issue by RexTheBean** [IrrigationProtocol/BugBounty#23]
Lange reported that when he attempted to buy $Water through the Sprinkler with ETH (not WETH) he was required to approve the use of ETH. This struck him as unusual as ETH isn't an ERC-20 token.

**Comment by Super-Genius** [comment]
I discussed it with him online.  This is actually a good thing as the contract then has gates built in to not spend too much of your ETH, since it is doing it as a proxy, this is good protection
