### ISSUE TITLE
MetaMask Tranche Approval Error

### ISSUE THREAD

**Issue by RexTheBean** [IrrigationProtocol/BugBounty#24]
mrchocoborider reports that:

"Every time I try to approve my tranche auction I get a metamask error: 

Message: Cannot read properties of undefined (reading 'length')

Code: TypeError"

![image](https://github.com/IrrigationProtocol/BugBounty/assets/145804523/054d09bc-9533-4425-ad6e-f53eed9f65fb)

**Comment by Super-Genius** [comment]
Going to close this, as I believe this is another bug in Metamask if the token is under ERC-20 tokens.
