### ISSUE TITLE
UI bug- Input exceeds balance 

### ISSUE THREAD

**Issue by CanadianBennett** [IrrigationProtocol/BugBounty#25]
Getting this error within the Claim model within the Water Tower, I have tried to input a smaller ETH amount
![image](https://github.com/IrrigationProtocol/BugBounty/assets/97637489/965a9b71-91ff-4656-849a-cfbf5b4e1d49)

**Comment by Super-Genius** [comment]
@CrabsAndTaxes can you Triage this and see if this is still and issue or was it User not having enough ETH?

**Comment by CrabsAndTaxes** [comment]
@Super-Genius  in order to test this properly I would need some claimable rewards.  Is it possible to add claimable ETH rewards to the faucet?  Or is this something that needs to trigger through the Irrigate function?

**Comment by Super-Genius** [comment]
I think Ruy added it for you to be able to test
