### ISSUE TITLE
Water Disappering After Withdrawal

### ISSUE THREAD

**Issue by nicktesla7** [IrrigationProtocol/BugBounty#26]
After withdrawing 1/5th of my water earlier today, it seems it is not registering the other 4/5 of water as staked.

![Irrigation Protocol](https://github.com/IrrigationProtocol/BugBounty/assets/146597121/c087c7d8-6cce-43be-a9c9-20c76f6eb1bd)

Here is the TX for deposit: https://etherscan.io/tx/0x2a28b5accabed9e8d879b1ff06446a6e32a6be94d0e2d4a4810f2156347f1026
Withdrawal: https://etherscan.io/tx/0x9a8f1f419f5daf935003d160db09c4d5ab0b199c8ca5120aa410b8501757560a

And the above is a screenshot of the UI not registering any stored water.

**Comment by CrabsAndTaxes** [comment]
Confirmed-Water balance now displays correctly
