### ISSUE TITLE
Water Tower Deposits ("Store") Not Working

### ISSUE THREAD

**Issue by harrysmiuff** [IrrigationProtocol/BugBounty#27]
several failed deposits by bruvs

<img width="957" alt="image" src="https://github.com/IrrigationProtocol/BugBounty/assets/145814724/5c5fa1bd-ae8a-4ea5-97be-4916798dc8c4">

**Comment by Super-Genius** [comment]
@ruymaster check these transactions and close this bug if the gasLimits.json fixed this

**Comment by ruymaster** [comment]
I checked the transaction. This error occurred before creating new pool at the first day of month. If new pools will be created in time, this error doesn't happen.
