### ISSUE TITLE
Creating Water auction is requiring $water as fee

### ISSUE THREAD

**Issue by LordJexxington** [IrrigationProtocol/BugBounty#30]
I have 32x un-stored $water available:

![image](https://github.com/IrrigationProtocol/BugBounty/assets/136977296/8bf656d1-9605-41be-818f-cc9927bf9bd8)

Create auction is drawing on $water as fee instead of ETH:

![image](https://github.com/IrrigationProtocol/BugBounty/assets/136977296/ec1354cd-f35c-4fb4-b785-bf68ca9b6e36)

**Comment by Super-Genius** [comment]
@CrabsAndTaxes Can you triage this one too, to see if it's done or reproducible with the new app-beta.irrigation.finance?

**Comment by CrabsAndTaxes** [comment]
Unable to replicate.  Fixed in updates.
