### ISSUE TITLE
Selecting either Tranches or WATER on the Create Auction page visually selects both

### ISSUE THREAD

**Issue by safisynai** [IrrigationProtocol/BugBounty#32]
Browser: Firefox 119.0a1 on Windows 11

On the Create Auction page, clicking either the Tranches or WATER button at the top of the page visually selects *both* Tranches and Water. This seems to just be a visual bug, as the rest of the UI correctly reflects which asset was selected.

Result of clicking WATER:
![image](https://github.com/IrrigationProtocol/BugBounty/assets/63223904/cfe0c4de-c25b-468e-9d97-4550a24008a4)

Result of clicking Tranches:
![image](https://github.com/IrrigationProtocol/BugBounty/assets/63223904/3edf841a-4766-43d2-80a1-993ededbcc5e)

**Comment by ruymaster** [comment]
Fixed

**Comment by ruymaster** [comment]
https://github.com/IrrigationProtocol/irrigation-dapp/commit/3faec7ddfd54289b67e41020daf252e97347356a

**Comment by Super-Genius** [comment]
verified
