### ISSUE TITLE
‘Settled Auctions’ included in count for ‘All Auctions’ 

### ISSUE THREAD

**Issue by bIc-bean** [IrrigationProtocol/BugBounty#33]
I would’ve expected the number in the brackets on the tab for # of auctions would correspond with number of visible auctions in the list. Currently low numbers but as ‘Settled’ goes up, this ‘All Auctions’ tab gets less intuitive. 

![Uploading
![IMG_8574](https://github.com/IrrigationProtocol/BugBounty/assets/146710449/f39e1742-9388-496d-b873-8dd4204b582a)
 IMG_8574.png…]()

**Comment by ruymaster** [comment]
Updated `All Auctions` into `All Active`.
