### ISSUE TITLE
Incorrect Math After Hitting "Max" in Auction

### ISSUE THREAD

**Issue by RexTheBean** [IrrigationProtocol/BugBounty#37]
I went into the Bean Auction posted in the Beta site with 20 DAI in my test wallet. When I clicked to bid "Max" next to the DAI amount in the Order Slip panel, the math went crazy, as shown here:

![image](https://github.com/IrrigationProtocol/BugBounty/assets/145804523/06cedc1f-26fd-4a99-bd43-a851896882da)

A similar issue if I performed the same task, but clicked "Max" next to the "You Receive" box:

![image](https://github.com/IrrigationProtocol/BugBounty/assets/145804523/178bf3fe-ef59-46a3-8f58-e314f0231a4b)

**Comment by RexTheBean** [comment]
@Super-Genius - Looking at this more, it appears to be due to how the Auction itself is set up. The minimum bid price was set to $1,000, therefore the Auction page automatically divides my Max DAI by 1000 to determine the rest of the bid calculations. 

So the math IS correct, but the auction parameters were so unusual that it looked like something was wrong. Not sure if this is a concern or not.

**Comment by sunderhus** [comment]
@Super-Genius  after @RexTheBean comment, this is still a bug? If yes, can you provide me the documentation or math formula used, so I can fix it?

**Comment by ruymaster** [comment]
I don't think it's a bug. If the user clicks MAX for the DAI amount, it is correct. This means that even if the user enters the total token balance, the result will be less than the minimum bid amount.
The second case is similar. This means that users must have sufficient token balance to bid for the total amount of auction tokens available.
