### ISSUE TITLE
Transparant Water Module

### ISSUE THREAD

**Issue by cmillisdumb** [IrrigationProtocol/BugBounty#5]
When clicking the top right water module the popup is transparent and difficult to read.  

<img width="998" alt="Screenshot 2023-09-22 at 9 15 40 AM" src="https://github.com/IrrigationProtocol/BugBounty/assets/121394839/4e75a3b1-5f15-4746-a420-6db746189d3c">

**Comment by Super-Genius** [comment]
do you have dark mode enabled?  Turn it off is so, I think it may over darken our dark theme

**Comment by cmillisdumb** [comment]
I don't, no. Just noticed it when testing.

**Comment by dr00-eth** [comment]
@cmillisdumb isn't water naturally transparent? :mega_kek:

**Comment by ruymaster** [comment]
Fixed
