### ISSUE TITLE
[UI Improvement] Mouse icon bug within the Farmers Market section

### ISSUE THREAD

**Issue by CanadianBennett** [IrrigationProtocol/BugBounty#8]
Each Tranche has a click box on the farmers market page within the tranche composition and shows the pointer icon mouse but nothing happens when I click.  

![image](https://github.com/IrrigationProtocol/BugBounty/assets/97637489/7d91ce47-df9e-462b-8f87-06a181bd43af)

**Comment by keshxyz1** [comment]
Nothing needs to be changed here aside from removing the interaction states. So when user is hovering on one of the items on Tranche Composition there should be no hover states.
